# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RaviTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RaviTest
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
